### ISSUE TITLE
HTML entities are encoded unexpectedly

### ISSUE THREAD

**Issue by whindsx** [nigelm/html-scrubber#18]
The module appears to apply HTML::Entities:encode_entities to the passed HTML string but does not decode the data afterwards. This is unexpected. 

Ex.
my $scrubber = HTML::Scrubber->new();
print $scrubber->scrub('2 > 1 is true');
2 &gt 1 is true

IMO if it's going to encode then it should decode when it's done.

This was also mentioned in the 0.15 CPAN rating/review: https://cpanratings.perl.org/dist/HTML-Scrubber

**Comment by nigelm** [comment]
I believe it is performing the encode to deal with the implicit decode that happens in `HTML::Parser` as described in https://metacpan.org/pod/HTML::Parser#Argspec

Since `HTML::Parser` has already assymetrically played with the entity encoding, there is not really anything that can be done to completely fix this short of a psychic parser.  Encoding the values of the attributes is probably the best compromise.

**Comment by nigelm** [comment]
I suspect the problem you are seeing is not due to the encode, but due to the fix for RT#2991

https://rt.cpan.org/Public/Bug/Display.html?id=2991

Appropriate suggestions would be considered, but need to consider the primary use case is the handling of untrusted HTML input.

**Comment by whindsx** [comment]
I can live with it. Thanks for the background.

**Comment by bschmalhofer** [comment]
This is an old issue, but I have run into a case where encoding  `>` as `&gt;` has a bad effect. It is with CSS that uses a child combinator. At least Chrome and Firefox show the paragraph as golden, but the span not as silver.

```
<html>
<head>
  <title>A Meaningful Page Title</title>
  <style>
    div > p {
        background-color: gold;
        border: 1px solid gray;
    }
    div &gt; span {
        background-color: silver;
        border: 1px solid gray;
    }
  </style>
</head>
<body>
<div><p>gold</p</div>
<div><span>silver</span</div>
<body>
</html>

```
